### PR TITLE
implement assign command

### PR DESCRIPTION
**Pull request by dsap**
I've followed your recommendation on implementing a general solution for memory mapped devices with re-assignable address. At the moment, it works for SIO (hence some structures are temporarily located in sioemu.h).

test example:
a) boot cpm2.dsk -> should work
b) assign SIO0_STATUS 80
assign SIO0_DATA 81
loadhex scm.hex
run 0 -> should work correctly.

regards
Dimitris

### CODE REVIEW

**Comment by jblang** [comment]
Thanks for submitting this. I will try to get it merged soon.

**Comment by dsap** [comment]
Hi J.B,

I am also thinking of implementing a mechanism to load a configuration file (if it exists on the SD) and populate the device structure.  The file can be loaded before autoexec.z8c so that the user can put any attach commands in the later.  Let me know what you think.

**Comment by jblang** [comment]
I had a chance to look over your changes. I would like to request a few tweaks before I merge it:

- Make sure your code adheres to [K&R style](https://en.wikipedia.org/wiki/Indentation_style#K&R_style). Mostly I noticed that you are missing some spaces around operators, braces, and the like. 
- Remove the Makefile changes from your commit
- Rename DEVICE to device_t to match conventions used elsewhere in my code.
- Move generally applicable definitions like port_rd, port_wr, device_t (renamed from DEVICE), write_dev_tbl, read_dev_tbl, device_registry, and the init_devs function to iorq.h/iorq.c
- Move definitions of SIO-related devices from cli.c to sioemu.c and add externs to sioemu.h if necessary.

I like the idea of saving configuration to a file (preferably human readable), and I would also like this to be general purpose to store mounts, baud rate, and other persistent configuration.  That should probably be a separate PR though.

A few other ideas (not within the scope of this PR):

- Combine the functionality of the assign and attach commands so files can be directly attached to a port without having to go through both assign and attach. The AVR's UART 0 and UART 1 could then be treated as special files.
- Allow stdin/stdout/stderr used by the stdio functions to be reassigned to either UART 0 or UART 1, or a file (maybe via a separate command).
- I am working on an output only terminal emulator on the TMS9918A (there is a tms_putchar function in tms.c that works like a UART's putc). Currently I have been testing this by calling it from uart_putc so that anything sent to the UART is echoed to the TMS9918A. However, I would eventually like to be able to assign it to a separate port just like the serial ports.

**Comment by jblang** [comment]
I didn't hear back from you regarding the changes I requested, but meanwhile I started on a more general version of this feature that will allow assigning any device to any port (not just serial). I will check it in as soon as I get it debugged. Just wanted to let you know so you wouldn't waste any effort on this.

**Comment by dsap** [comment]
I see.  Thanks for informing me JB.  So this PR can be closed now.

**Comment by jblang** [comment]
FYI, I have checked in my version now.  It has an assign command that will let you assign any port to any device supported by z80ctrl. It also scans for external devices and has safeguards to prevent you from assigning to a port used by an external device.  I tested it out with SCM and it works as expected if I assign the UART registers to 80/81.  I plan to add more features like autodetecting where external devices are located, such as the TMS9918 and RomWBW 512K RAM/ROM board.

I'm sorry I didn't end up using your code. As I was contemplating merging it, I decided I could build a more general mechanism.

**Comment by dsap** [comment]
No worries.  I was too late to cleanup my code anyway.  I will soon pull your new code to use and test it.  I really like this project so I will find something else to work on in the future :)

**Pull request closed without merging**
